language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsessentials4linuxlabs
  api_key:
    secure: EJaMwWxAw+OmAYtCcy8fHOUcRiAuKXR1NEGwchQnkKp2MbrrscQqRqEPwslyaFKgay6TLAqI2Rqq2pXUXRdmJlSXSndbq584yV432RN99YfAbamSRRcX0Un1DvkdG+zr4u8CoGNGZ80lGv2gN8hhGPcx93Nf9BMCjvTxqYhEVJi9YZJr25w6mfHcwZ24Xm2fvs2/QIUg67eG/sLeg+0WFR4ZYYlEXl/ZCYUGIKXjHwOwRfduNnoW8YA3xrCR4RuTuIn4yM4nfECtjJf2Pfzu785IEVxZ29Tjda4M/6usF1yQESLhIyuIXY8a5hFkDI5J9UW2VAH+XQ9VrNkeu6KakAfSp7cgVC3irhGu3lGJkOwjkEN/iPawkY7wqXn/FVnPNim9KicXB3GBrLpheAvY6tCd0cqyPC2VSMBlefDMxGxIAgA8BbSENuGdwJ05Bl+xG81rSZ0YjcVqetl0OcAnZ6V1Q0x0w+lkBUFm+xfdKKilPXwdEhMdlUPCWCnuogoDe+R10nUHIMyB4w8Jq8XswCijlyLXtgC/24aNYLH7iwhkKHCF2IRGuUHq+LrosTJbfGSZKtPEmuWYhtZPFzTNjYjffuErttRcUt0ZdZTxCBJ2FikKggNmO4JOL1piaByfNvJprzdD+h59R1HjJw2GONpb4+q/WHePlkwCCjpUI6w=
